#!/usr/bin/env bash
#
# Unit fixture for ngx_http_compression_ratio_parts() -- the overflow-safe
# $compression_ratio integer/fractional split (the parent's #294 shape,
# re-derived for this module's helper).
#
# The function is EXTRACTED VERBATIM by line range and compiled standalone,
# so a hand-copied duplicate of the arithmetic cannot quietly drift from
# production. No nginx tree and no compression library needed: pure C,
# self-contained, checked against an unsigned __int128 oracle.
set -euo pipefail

cd "$(dirname "$0")/.."

SRC=ngx_http_compression_module.c
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/compression-ratio-scaling-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

sig="$(grep -n '^ngx_http_compression_ratio_parts(uint64_t bytes_in' "$SRC" \
       | head -1 | cut -d: -f1)"
if [ -z "$sig" ]; then
    echo "FAIL: could not locate ngx_http_compression_ratio_parts() in $SRC" >&2
    exit 1
fi

start=$((sig - 1))
rel="$(tail -n "+${sig}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
end=$((sig + rel - 1))

{
    echo "/* Generated by test_ratio_scaling_unit.sh -- verbatim extraction"
    echo " * from $SRC lines ${start}-${end}. Do not edit. */"
    sed -n "${start},${end}p" "$SRC"
} >"$OUT/generated_ratio_parts.inc"

# The production variable must actually route through the helper: a
# reintroduced inline `* 1000 /` would leave this fixture green while
# the variable overflowed again.
if grep -q 'bytes_in \* 1000 / ctx->bytes_out' "$SRC"; then
    echo "FAIL: \$compression_ratio no longer routes through ratio_parts()" >&2
    exit 1
fi
if ! grep -q 'ngx_http_compression_ratio_parts(ctx->bytes_in, ctx->bytes_out' \
        "$SRC"; then
    echo "FAIL: \$compression_ratio no longer calls ratio_parts()" >&2
    exit 1
fi

cp tools/test_ratio_scaling_unit.c "$OUT/"
"$CC" -std=gnu99 -O2 -Wall -Wextra -Werror -I"$OUT" \
    -o "$OUT/test_ratio_scaling_unit" "$OUT/test_ratio_scaling_unit.c"
timeout 60s "$OUT/test_ratio_scaling_unit"
